### ISSUE TITLE
Dump page rarely works

### ISSUE THREAD

**Issue by akatakritos** [theaigames/next#1]
Often times the dump page for a match is just a white screen, or will show the header, footer, and spinner without ever showing the IO log.

My bot writes logs to standard error, and I would like to be able to see what it's thinking when I lose matches, but the dump page almost never works.

Here's an example page that is failing:
https://booking.riddles.io/competitions/hack-man/match/a78136cb-9a19-432a-8f8b-1f432f6ec327/dump

```
Uncaught TypeError: Cannot read property 'get' of undefined(…)
app.js:3 Uncaught TypeError: Cannot read property '__reactInternalInstance$seqkx3tnnltsgrzl0m3kawcdi' of null(…)
app.js:31 Uncaught TypeError: Cannot read property 'get' of undefined(…)
app.js:3 Uncaught TypeError: Cannot read property '__reactInternalInstance$seqkx3tnnltsgrzl0m3kawcdi' of null(…)
```

If I open it in incogneto mode, I don't get the React errors, but I do get the error about reading the `get` property from undefined.

**Comment by nikovanmeurs** [comment]
We have some stability issues with the API, causing page loading times to fluctuate quite a lot. We're looking into this but haven't found a solution yet. The React errors will be resolved with the next big front end update, which will land somewhere in November.
