### ISSUE TITLE
C# Compile Errors

### ISSUE THREAD

**Issue by bw3740** [theaigames/next#2]
We haven't been able to compile a C# bot since 11/2/2016 1pm CST.

Errors

WARNING: Your kernel does not support swap limit capabilities, memory limited without swap. warning CS8001: SDK path could not be resolved error CS0016: Could not write to file `run_ai'. Could not find a part of the path "/compiler_dir/bot_043f937e-f6fc-4f99-9a79-66d727f555a0_27-compiled/run_ai".

Output

Note: dmcs is deprecated, please use mcs instead! Compilation failed: 1 error(s), 1 warnings

**Comment by nikovanmeurs** [comment]
The compiler has been updated. Please let us know if you still experience problems when uploading your bot.

**Comment by nikovanmeurs** [comment]
The compiler running on production contained an older version of the C# compile script. The script has been updated and we've been able to compile C# bots successfully again.

Please let us know if you're still experiencing problems.
