### ISSUE TITLE
Leaderboard not loading

### ISSUE THREAD

**Issue by mpricope** [theaigames/next#6]
Hey guys,

I don't know if I am just unlucky, but for me the Leaderboard doesn't want to load since the last update.

**Comment by CaneloDigital** [comment]
I tried now and it worked for me...

**Comment by nikovanmeurs** [comment]
Fetching the leaderboard data is quite heavy on the api. At the moment you have about a 50/50 chance for the request to simply time out after a minute.

Improving the performance of the API servers is our main priority at the moment. We hope to have a more performant API live in about 1 - 2 weeks.
